# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - mkdir .cert
  - cp -r /.well-known/acme-challenge/* .cert
  - mv .cert public
  artifacts:
    paths:
    - public
  only:
  - master
