# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  - mkdir .public
  - mkdir .public/.well-known
  - mkdir .public/temp
  - mkdir .public/.well-known/acme-challenge
  - cp -r .well-known/acme-challenge/* .public/.well-known/acme-challenge/
  - cp -r *.html .public/temp
  - for file in .public/temp/*.html; do mv "$file" "${file%.*}"; done
  - mv .public/temp/* public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
